language: android
jdk: oraclejdk7

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23

    #Include support Libs
    - extra-android-m2repository
    - extra-android-support
    
script:
    - ./gradlew clean test --info